export const skillCategoryOptions = [
  {title: 'Frontend', value: 'frontend'},
  {title: 'Backend', value: 'backend'},
  {title: 'Full Stack', value: 'fullstack'},
  {title: 'Data', value: 'data'},
  {title: 'DevOps', value: 'devops'},
  {title: 'Testing', value: 'testing'},
  {title: 'Collaboration Tools', value: 'collaboration'},
  {title: 'Project Management', value: 'project-management'},
  {title: 'Soft Skill', value: 'soft'},
  {title: 'CLI & Tooling', value: 'tooling'},
  {title: 'Documentation', value: 'documentation'},
  {title: 'Security', value: 'security'},
  {title: 'AI / Automation', value: 'ai'},
  {title: 'Mathematics', value: 'math'},
  {title: 'Scientific Skills', value: 'sci'},
  {title: 'Computer Science', value: 'cs'},
  {title: 'Software Engineering', value: 'swe'},
  {title: 'Engineering', value: 'engineering'},
  {title: 'Other', value: 'other'},
]
